### ISSUE TITLE
error invalid URL 

### ISSUE THREAD

**Issue by xflihaibo** [sidorares/node-wrk#14]
node v10.15.3
wrk v4.1.0

err:  { Error: Command failed: wrk -t2 -c1000 -d10s --latency  http://localhost:3000
invalid URL:

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:597:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'wrk -t2 -c1000 -d10s --latency  http://localhost:3000' }
out:  undefined

index.js 
line 31   cmd += ' ' + opts.url;===>cmd += opts.url

**Comment by Rob-Page** [comment]
I found this to be due to the, "printLatency: true" parameter. This generates the --latency parameter in the cmd with two spaces after it, and before url. This causes the url to be detected as a blank space. If you remove the printLatency it should resolve the issue.
